// Curated icon-name -> lucide-react component map, offered by the "icon"
// field kind (icon/infobox elements). Split out of Designer.tsx as part of
// Layer 1b (Inspector/ElPreview extraction, see
// docs/superpowers/specs/2026-08-20-designer-tsx-refactor-design.md) — a
// plain module-level lookup table with zero closure dependency on Designer()
// state, but ElPreview.tsx needs it directly and designer/ files can never
// import back from Designer.tsx (see designer/types.ts's own note), so it
// has to live in designer/ too.
//
// SectionBlock.astro hardcodes the matching raw SVG path for each of these
// names (no lucide-react dependency on the frontend) — add to both places
// together.
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  AlertCircle,
  AlertTriangle,
  Archive,
  AtSign,
  Award,
  BarChart3,
  Battery,
  Bell,
  Bookmark,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Car,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  Coffee,
  Compass,
  CreditCard,
  DollarSign,
  Download,
  Dumbbell,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Film,
  Flag,
  Folder,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Inbox,
  Info,
  Laptop,
  Leaf,
  Link2,
  Lock,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Music,
  Package,
  Percent,
  Phone,
  PhoneCall,
  PieChart,
  Plane,
  Printer,
  QrCode,
  Receipt,
  Recycle,
  Rocket,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tablet,
  Tag,
  Target,
  ThumbsDown,
  ThumbsUp,
  Train,
  TrendingUp,
  Truck,
  Umbrella,
  Unlock,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Wifi,
  XCircle,
  Zap,
} from "lucide-react";

export const ICONS: Record<string, typeof Check> = {
  check: Check,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  star: Star,
  phone: Phone,
  mail: Mail,
  "map-pin": MapPin,
  calendar: Calendar,
  clock: Clock,
  "external-link": ExternalLink,
  "chevron-right": ChevronRight,
  download: Download,
  menu: Menu,
  home: Home,
  search: Search,
  user: User,
  users: Users,
  settings: Settings,
  bell: Bell,
  heart: Heart,
  share: Share2,
  bookmark: Bookmark,
  eye: Eye,
  "eye-off": EyeOff,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  "shield-check": ShieldCheck,
  globe: Globe,
  link: Link2,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  "alert-triangle": AlertTriangle,
  "alert-circle": AlertCircle,
  info: Info,
  "help-circle": HelpCircle,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  gift: Gift,
  tag: Tag,
  flag: Flag,
  award: Award,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  percent: Percent,
  wallet: Wallet,
  receipt: Receipt,
  store: Store,
  package: Package,
  truck: Truck,
  briefcase: Briefcase,
  building: Building2,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  send: Send,
  inbox: Inbox,
  archive: Archive,
  "at-sign": AtSign,
  "phone-call": PhoneCall,
  camera: Camera,
  video: Video,
  music: Music,
  mic: Mic,
  image: ImageIcon,
  "file-text": FileText,
  folder: Folder,
  printer: Printer,
  film: Film,
  smartphone: Smartphone,
  monitor: Monitor,
  laptop: Laptop,
  tablet: Tablet,
  headphones: Headphones,
  wifi: Wifi,
  battery: Battery,
  cloud: Cloud,
  "qr-code": QrCode,
  sun: Sun,
  moon: Moon,
  umbrella: Umbrella,
  compass: Compass,
  map: Map,
  car: Car,
  plane: Plane,
  train: Train,
  rocket: Rocket,
  coffee: Coffee,
  utensils: Utensils,
  dumbbell: Dumbbell,
  stethoscope: Stethoscope,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "trending-up": TrendingUp,
  "bar-chart": BarChart3,
  "pie-chart": PieChart,
  activity: Activity,
  zap: Zap,
  handshake: Handshake,
  target: Target,
  recycle: Recycle,
  leaf: Leaf,
  sparkles: Sparkles,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "arrow-up-right": ArrowUpRight,
};
